my_site:
    image: ubuntu-django:1.0
    container_name: my_site
    restart: always
    volumes:
        - /home/data/docker/my-site3:/opt/django/project
        - /home/data/docker/my-site3/logs:/opt/django/logs
        - /home/data/docker/my-site3/venv:/opt/django/venv
        - /home/data/.ssh:/root/.ssh
    ports:
        - "8000:8000"
