my_site_supervisor:
    image: ubuntu-django-supervisor:1.0
    container_name: my_site_supervisor
    restart: always
    volumes:
        - /home/data/docker/my-site3:/opt/django/project
        - /home/data/docker/my-site3/logs_supervisor:/opt/django/logs
        - /home/data/docker/my-site3/venv_supervisor:/opt/django/venv
        - /home/data/.ssh:/root/.ssh
